// Generated by CoffeeScript 1.11.1
(function() {
  angular.module('tmsApp', ['ngRoute']).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/login', {
        templateUrl: './app/login/index.html',
        controller: 'LoginCtrl'
      }).when('/regist', {
        templateUrl: './app/regist/index.html',
        controller: 'RegistCtrl'
      }).when('/', {
        templateUrl: './app/index/index.html',
        controller: 'IndexCtrl'
      });
    }
  ]).run([
    '$location', function($location) {
      return $location.path('/login').replace();
    }
  ]);

}).call(this);

//# sourceMappingURL=index.js.map
