// Generated by CoffeeScript 1.11.1
(function() {
  var db, isUserExists, jwt, login, regist;

  db = require('./../libs/db');

  jwt = require('jsonwebtoken');

  login = function(req, res, next) {
    var password, username;
    username = req.body.username;
    password = req.body.password;
    console.log("username=" + username + " pwd=" + password);
    return db.users.findOne({
      username: username,
      password: password
    }, function(err, user) {
      var expiredTime, token;
      console.log(user);
      if (err) {
        return next(err);
      }
      if (!user) {
        return next(new Error('登陆失败'));
      }
      token = jwt.sign({
        username: username
      }, 'lvlay');
      expiredTime = Date.now() + 1000 * 60 * 60 * 24;
      return db.users.update({
        _id: user._id
      }, {
        $set: {
          token: token,
          expiredTime: expiredTime
        }
      }, {
        upsert: false
      }, function(err, num) {
        console.log("num=" + num);
        if (err) {
          return next(err);
        }
        if (num === 0) {
          return next(new Error('登陆失败,请重试'));
        }
        return res.json({
          token: token
        });
      });
    });
  };

  isUserExists = function(req, res, next) {
    var body;
    body = req.body;
    if (!body || !body.username || !body.password) {
      return next(new Error('请提交用户注册信息'));
    }
    return db.users.findOne({
      username: req.body.username
    }, function(err, user) {
      if (err) {
        return next(err);
      }
      if (user) {
        return next(new Error('用户名已存在,请重新注册'));
      }
      next();
    });
  };

  regist = function(req, res, next) {
    var body, postData;
    body = req.body;
    console.log('bbbb');
    postData = {
      username: body.username,
      password: body.password,
      token: '',
      expiredTime: Date.now()
    };
    console.log('cccc');
    db.users.insert(postData, function(err, user) {
      console.log(user);
      if (err) {
        return next(err);
      }
      return res.json(true);
    });
  };

  module.exports = {
    isUserExists: isUserExists,
    regist: regist,
    login: login
  };

}).call(this);

//# sourceMappingURL=userBiz.js.map
