// Generated by CoffeeScript 1.11.1
(function() {
  var db, express, router;

  express = require('express');

  router = express.Router();

  db = require('./../libs/db');

  router.get('/faq', function(req, res, next) {
    console.log('进入faq');
    return db.users.insert({
      username: 'tom'
    }, function(err, user) {
      if (err) {
        return next(err);
      }
      console.log(user);
      res.json(user);
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=api.js.map
