// Generated by CoffeeScript 1.11.1
(function() {
  var commonBiz, express, router, taskBiz;

  express = require('express');

  router = express.Router();

  taskBiz = require('./../biz/taskBiz');

  commonBiz = require('./../biz/commonBiz');

  router.post('/task', commonBiz.setUserInfo, commonBiz.validateUserinfo, taskBiz.addTask);

  router.put('/task', commonBiz.setUserInfo, commonBiz.validateUserinfo, taskBiz.updateTask);

  router.get('/task/:id', commonBiz.setUserInfo, commonBiz.validateUserinfo, taskBiz.getTask);

  router.get('/task', commonBiz.setUserInfo, commonBiz.validateUserinfo, taskBiz.getTasks);

  module.exports = router;

}).call(this);

//# sourceMappingURL=task.js.map
