// Generated by CoffeeScript 1.11.1
(function() {
  var path;

  path = require('path');

  module.exports = {
    port: 7410,
    dbFilePath: path.join(__dirname, './../database/')
  };

}).call(this);

//# sourceMappingURL=config.js.map
