// Generated by CoffeeScript 1.11.1
(function() {
  angular.module('tmsApp').controller('IndexCtrl', [
    '$scope', '$rootScope', '$location', function($scope, $rootScope, $location) {
      return 1;
    }
  ]);

}).call(this);

//# sourceMappingURL=indexCtrl.js.map
