// Generated by CoffeeScript 1.11.1
(function() {
  angular.module('tmsApp').controller('RegistCtrl', [
    '$scope', '$http', '$location', 'tmsUtils', function($scope, $http, $location, tmsUtils) {
      $scope.userEntity = {
        username: '',
        password: '',
        password2: ''
      };
      return $scope.doReg = function() {
        if ($scope.userEntity.password !== $scope.userEntity.password2) {
          return alert('两次密码不一致');
        }
        if (!$scope.userEntity.username || !$scope.userEntity.password || !$scope.userEntity.password2) {
          return alert('用户名密码不允许为空');
        }
        return $http.post(Tms.apiAddr + "/api/user/regist", $scope.userEntity).then(function(res) {
          alert('注册成功');
          return $location.path('/login');
        }, tmsUtils.processHttpError);
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=registCtrl.js.map
