// Generated by CoffeeScript 1.11.1
(function() {
  angular.module('tmsApp').factory('tmsUtils', [
    function() {
      var processHttpError;
      processHttpError = function(res) {
        var data;
        console.log(res);
        data = res.data;
        if (data.message) {
          return alert(data.message);
        }
      };
      return {
        processHttpError: processHttpError
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=tmsUtils.js.map
