// Generated by CoffeeScript 1.11.1
(function() {
  angular.module('tmsApp').controller('LoginCtrl', [
    '$scope', '$http', '$location', 'tmsUtils', function($scope, $http, $location, tmsUtils) {
      $scope.userEntity = {
        username: '',
        password: '',
        rememberMe: false
      };
      return $scope.doLogin = function() {
        return $http.post(Tms.apiAddr + "/api/user/login", $scope.userEntity).then(function(res) {
          console.log($scope.userEntity);
          return $location.path('/').replace();
        }, tmsUtils.processHttpError);
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=loginCtrl.js.map
